# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(verbose_name='date answered')),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='no description yet!', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date asked'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
